sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "eqqGdfmzNyEwG2Bn/wiU+FP+BgSiA/B9d0+/kLvsvSWGJYS7i2oxBaTLK5lED07XHJPfBBSjrZb0o5Gf4RWuAGBPSvSqM8H8DGY0akX+CtAGD7zZGAM3lVOGSeC5LfEzCUOUmY1RXslymN4924+ITtgL7vxlRnExR3kxKP23Ln2OWBmsMcM/jqARisvLAZ/ff37U+lxQgoRXiVKBSJwiFHX2YlDtddl0dh5S6x/uCKf+vHNiKKkE/ghTitavv1CP81MaW7zuzz+qLMxTr25B4t2CRhH/0iINTmwgutOEPnOuAj7t/BU7s+oy+PTUKpFIA2M9CIW6BX48rmAa+rfATG6Qvu5GX02ImUwX827xl3d1SJxVSh+znRrFW6KA9LcHSV+kHVpTktgTBkvRD47Yy6dlfx59/d59Wkb5691/LFc0EuXqyHUkXEXx/GW5DWjX6a8Mp33nQUw9pxv40YNXGJQz1EuHSE+WNjbxYCH+nJ5nk+3I+yX4Hp0NWgZt0MFLuyhpqUr8051BrfERKnQbB2ESF/iKlaZEaJlDc6HqMC7y+Bh/z4sET2j58tTlLS98nrBMQfPEJ3LukZbBPw5lXvvNWvg9m6JDAY446kOcOewuXZ4QH0lVdXWHzjPzwvSQYS0w2fa6rfH/e+Q8KCXCK3B3tJ0ASDxeDrSPpwFkc8I="
    # AWS_SECRET_ACCESS_KEY
    - secure: "mc0seNF6uL4L97E8gGBog/roTNb4FK8kwq6W3bF3RC6IU6pXWH1OKlRJxph3aeV/t8etC+TJarpMaw3IbBmsLEwWFm0meKX+LmtMfrV9YBWCKo0OLzqXRnRiaicfUjZ2H9BS9yOJsz0vHUKIHgfydsAe7M4k66zHP7KzEUWtkjlp+fmuv6SefPC69FboZrRdpf8P1eaOH5hk7G6GNkSAQVC3KaapaCbgslbphTZYk0Ew9Ixx1inXyN+EFkDmbQnE/xTVrbbyDXX/ZQ/DG0Ra1t3f6PvDjUhjPIa85T7wJVl41YMZ3Xd50VxEopqig+A2Hka+oQh49cyvmZVIUquOLGCtY2Uow7Vd6IxqQ5XjhXvI419pJZauezCX5WPB4jWpxZESiCg+noLjmNHAz7Z/c79gRYjT9bL8xccQ70FQPiE75FmdCF/Iml0CPI4diHjckIkaF5WJHJdfPJ1a+YO6MpO1MXGlWF+hL//p9f46aDitbLyS+inPp9rNqrradR09XhxkkV/bFa9PKuM7EX36UrdZu431Tei77sOKAO0LcEAfzVFmHEyJHyEucIeSGCvnG8MZaHdR/9RoXjbpwmtssIOyrBYFwUsipvN463L5sk2c2/3KAPZDzqz7464An0vUjb4oKXB/EIAKzYgtoo9TaIxbPlTbeVdREprBw620vb8="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="henkilotietomuutos"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv target/henkilotietomuutospalvelu-*.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr src/main/resources/* $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
