spring:
  mandatory-file-encoding: UTF-8
  profiles.active: default
  jackson:
    serialization:
      write-dates-as-timestamps: true
  flyway:
    enabled: true
    out-of-order: true
    # Only for initial migration for non-empty DB. Change to false after prod installation.
    baseline-on-migrate: true
    baseline-version: 2018022615382893874
    table: flyway_schema_history

server:
  servlet:
    context-path: /henkilotietomuutos-service

# console
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    org.hibernate.SQL: error
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error

