spring:
  mandatory-file-encoding: UTF-8
  profiles.active: default
  jackson:
    serialization:
      write-dates-as-timestamps: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  flyway:
    enabled: true
    out-of-order: true
    # Only for initial migration for non-empty DB. Change to false after prod installation.
    baseline-on-migrate: false
    baseline-version: 2018022615382893874
    table: flyway_schema_history
  jpa:
    properties:
      # https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    cache-names: koodisto

server:
  servlet:
    context-path: /henkilotietomuutos-service

# console
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    org.hibernate.SQL: error
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error

